# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Build and test
      run: swift test -v --parallel --enable-test-discovery
      
  # build:
  #   name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #       swift: ["6.0.0"]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
  #       with:
  #         swift-version: ${{ matrix.swift }}
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: swift build -v
  #     - name: Run tests
  #       run: swift test -v
